version: '3.4'

services:
  rabbitmq:
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq 
      RABBITMQ_DEFAULT_PASS: "12345"
  
  mysql:
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "12345"
        MYSQL_DATABASE: "chats_db"

  phpmyadmin:
    ports:
        - "8081:80"
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: "12345"
        PMA_HOST: mysql